manifest:
  remotes:
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: not-in-stock
      url-base: https://github.com/not-in-stock
  projects:
    - name: zmk
      remote: not-in-stock
      revision: caksoylar/zen-v1+v2+mmv+ts
      import: app/west.yml
  self:
    path: config
